'use client';
import {useRef,useState} from 'react';
import AccountNav from '@/components/account-nav';
import type { SiteUser } from '@/lib/auth/session';
import {ArrowDown,ArrowRight,Check,CheckCheck,Copy,Download,FileText,Info,LoaderCircle,ScanLine,ShieldCheck,Sparkles,Upload,X,LockKeyhole,ChevronRight} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {CV,Scan,labels,toPlainText} from '@/lib/cv';
import type {PDFStyle} from '@/lib/pdf';
type Result={kind:'scan';data:Scan}|{kind:'optimize';data:CV;headings:typeof labels};
const education="Un ATS (Applicant Tracking System) est un logiciel que les entreprises utilisent pour recevoir, trier et classer les candidatures. Quand tu postules en ligne, ton CV passe souvent par lui avant qu'un humain ne le voie. Il lit le texte de ton CV, le compare à l'annonce, et classe les candidats. L'ATS ne te refuse presque jamais tout seul — il y a toujours un recruteur derrière —, mais un CV mal formaté ou pauvre en mots-clés peut être classé si bas qu'il n'est jamais consulté. Le but n'est pas de tromper le logiciel, mais que ton vrai profil soit bien lu et bien classé.";
export default function Workspace({user}:{user:SiteUser}){
 const [cv,setCV]=useState(''),[job,setJob]=useState(''),[busy,setBusy]=useState<''|'import'|'optimize'|'scan'>(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[result,setResult]=useState<Result|null>(null),[style,setStyle]=useState<PDFStyle>('modern'),[pdfBusy,setPdfBusy]=useState(false),[copied,setCopied]=useState(false),[filename,setFilename]=useState('');
 const fileInput=useRef<HTMLInputElement>(null);const resultRef=useRef<HTMLElement>(null);
 function changed(value:string,which:'cv'|'job'){if(which==='cv'){setCV(value);setFilename('');}else setJob(value);setResult(null);setError('');setNotice('');}
 async function importFile(file?:File){
  if(!file)return;setError('');setNotice('');
  if(!/\.(pdf|docx)$/i.test(file.name)){setError('Choisis un fichier .pdf ou .docx.');return;}
  if(file.size>4*1024*1024){setError('Le fichier doit faire moins de 4 Mo.');return;}
  setBusy('import');
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);
  try{const body=new FormData();body.append('file',file);const response=await fetch('/api/import',{method:'POST',body,signal:controller.signal});const data=await response.json() as {text:string;error:string};if(!response.ok)throw new Error(data.error);setCV(data.text);setFilename(file.name);setResult(null);setNotice('Texte importé. Vérifie son contenu avant de lancer l’analyse.');}catch(e){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'L’import n’a pas abouti. Réessaie ou colle le texte manuellement.');}finally{clearTimeout(timer);setBusy('');if(fileInput.current)fileInput.current.value='';}
 }
 async function analyze(mode:'optimize'|'scan'){
  setError('');setNotice('');if(cv.trim().length<30){setError('Ajoute ton CV (au moins 30 caractères) avant de lancer l’analyse.');return;}if(mode==='optimize'&&job.trim().length<30){setError('Ajoute l’annonce d’emploi (au moins 30 caractères) pour optimiser ton CV.');return;}
  setBusy(mode);setResult(null);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);
  try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,cv,job}),signal:controller.signal});const data=await response.json() as Result & {error:string};if(!response.ok)throw new Error(data.error);setResult(data);setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),60);}catch(e){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'L’analyse a pris trop de temps. Réessaie.');}finally{clearTimeout(timer);setBusy('');}
 }
 async function copy(){if(result?.kind!=='optimize')return;try{await navigator.clipboard.writeText(toPlainText(result.data,result.headings));setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('La copie automatique est indisponible. Sélectionne le texte du CV pour le copier.');}}
 async function download(){if(result?.kind!=='optimize')return;setPdfBusy(true);setError('');try{const {downloadCV}=await import('@/lib/pdf');await downloadCV(result.data,style,result.headings);}catch{setError('Le PDF n’a pas pu être généré. Réessaie ; le texte reste copiable.');}finally{setPdfBusy(false);}}
 return <div className="app-shell">
  <header className="site-header"><div className="header-inner"><a href="#" className="brand" aria-label="CV-ATS, accueil"><span className="brand-icon"><FileText size={22}/></span>CV<span className="brand-dash">—</span>ATS</a><nav aria-label="Navigation principale"><a href="#atelier" className="nav-active">L’atelier CV</a><a href="#comprendre">Comprendre les ATS <ArrowDown size={14}/></a></nav><AccountNav user={user}/></div></header>
  <main>
   <section className="workspace" id="atelier">
    <div className="intro"><div><p className="eyebrow"><span/> UN CV FIDÈLE. MIEUX COMPRIS.</p><h1>Ton parcours mérite<br className="mobile-break"/> d’être <span>bien lu.</span></h1><p className="intro-description">Adapte ton CV à une annonce, sans jamais inventer ton expérience.</p></div><div className="honesty-note"><ShieldCheck size={21}/><div><strong>100 % ton parcours</strong><span>On reformule. On n’invente rien.</span></div></div></div>
    <div className="editors">
     <article className="editor-card"><div className="editor-heading"><div className="editor-title"><span className="step">01</span><label htmlFor="cv">Ton CV</label></div><button className="import-button" disabled={!!busy} onClick={()=>fileInput.current?.click()}>{busy==='import'?<LoaderCircle size={16} className="spin"/>:<Upload size={16}/>}Importer un fichier</button><input ref={fileInput} type="file" accept=".pdf,.docx" onChange={e=>importFile(e.target.files?.[0])} className="sr-only" tabIndex={-1} aria-label="Importer un CV au format PDF ou DOCX"/></div>
      <div className="editor-meta"><span>Le point de départ : ton vrai parcours.</span><span>PDF, DOCX · 4 Mo max.</span></div>
      <textarea id="cv" value={cv} disabled={!!busy} maxLength={40000} onChange={e=>changed(e.target.value,'cv')} placeholder={'Colle le texte de ton CV ici…\n\nTes coordonnées\nTon expérience professionnelle\nTes compétences\nTa formation'} spellCheck={false}/>
      <div className="editor-footer"><span>{filename?<><FileText size={13}/>{filename}</>:<><LockKeyhole size={13}/>Texte modifiable, jamais enregistré</>}</span><span>{cv.length.toLocaleString('fr-FR')} / 40 000</span></div>
     </article>
     <article className="editor-card"><div className="editor-heading"><div className="editor-title"><span className="step">02</span><label htmlFor="job">L’annonce d’emploi</label></div><span className="tag">Le poste que tu vises</span></div><div className="editor-meta"><span>Pour faire ressortir ce qui compte.</span><span>Facultative pour le scan</span></div><textarea id="job" value={job} disabled={!!busy} maxLength={30000} onChange={e=>changed(e.target.value,'job')} placeholder={'Colle l’annonce d’emploi ici…\n\nL’intitulé du poste\nLes missions proposées\nLes compétences recherchées\nLe profil attendu'} spellCheck={false}/><div className="editor-footer"><span><Info size={13}/>Copie l’annonce complète pour plus de précision</span><span>{job.length.toLocaleString('fr-FR')} / 30 000</span></div></article>
    </div>
    <div className="action-bar"><div className="action-buttons"><button onClick={()=>analyze('optimize')} disabled={!!busy} className="primary-button">{busy==='optimize'?<LoaderCircle size={18} className="spin"/>:<Sparkles size={18}/>} {busy==='optimize'?'Optimisation en cours…':'Optimiser'}{busy!=='optimize'&&<ArrowRight size={17}/>}</button><button onClick={()=>analyze('scan')} disabled={!!busy} className="secondary-button">{busy==='scan'?<LoaderCircle size={18} className="spin"/>:<ScanLine size={18}/>} {busy==='scan'?'Analyse en cours…':'Scanner mon CV'}</button></div><span className="action-help">Une annonce pour optimiser.<br/>Ton CV suffit pour un premier diagnostic.</span></div>
    <div className="privacy-line"><ShieldCheck size={14}/><strong>Aucun CV ni annonce n’est stocké</strong><span>par CV-ATS.</span><a href="#confidentialite">En savoir plus</a></div>
    {error&&<div role="alert" className="message error"><Info size={18}/><p>{error}</p><button aria-label="Fermer le message d’erreur" onClick={()=>setError('')}><X size={16}/></button></div>}
    {notice&&<div role="status" className="message success"><Check size={18}/><p>{notice}</p></div>}
    <section ref={resultRef} className={'result-area '+(result?'has-result':'')} aria-label="Résultat" aria-live="polite" aria-busy={!!busy}>
     {!result&&!busy&&<div className="empty-result"><span className="empty-icon"><FileText size={26}/><span><Check size={10}/></span></span><h2>La prochaine version de ton CV commence ici.</h2><p>Ajoute tes textes, puis choisis une optimisation ou un scan.</p><div className="empty-features"><span><Check size={14}/> Fidèle à ton expérience</span><span><Check size={14}/> Lisible par les ATS</span><span><Check size={14}/> Prêt à copier ou télécharger</span></div></div>}
     {busy&&<div className="empty-result loading-result"><LoaderCircle className="spin" size={30}/><h2>{busy==='import'?'Extraction du texte…':busy==='scan'?'Lecture attentive de ton CV…':'Reformulation et vérification de ton CV…'}</h2><p>{busy==='import'?'Ton fichier est traité en mémoire.':'Cela peut prendre jusqu’à une minute. Garde cette page ouverte.'}</p></div>}
     {result?.kind==='optimize'&&<><div className="result-heading"><div><span className="eyebrow">TON CV, OPTIMISÉ</span><h2>Le même parcours. Les bons mots.</h2></div><button className="secondary-button small" onClick={copy}>{copied?<CheckCheck size={16}/>:<Copy size={16}/>} {copied?'Copié !':'Copier'}</button></div><p className="result-note">Relis chaque formulation avant d’envoyer ton CV : tu restes la référence pour ton parcours.</p><pre className="cv-output">{toPlainText(result.data,result.headings)}</pre><div className="export-bar"><div><label id="style-label">Ton style de PDF</label><Select value={style} onValueChange={v=>setStyle(v as PDFStyle)}><SelectTrigger aria-labelledby="style-label" className="style-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="modern">Moderne sobre</SelectItem><SelectItem value="finance">Finance classique</SelectItem><SelectItem value="minimal">Minimal aéré</SelectItem></SelectContent></Select></div><span className="export-note">Une colonne.<br/>Du vrai texte sélectionnable.</span><button className="primary-button" disabled={pdfBusy} onClick={download}>{pdfBusy?<LoaderCircle className="spin" size={17}/>:<Download size={17}/>} {pdfBusy?'Création du PDF…':'Télécharger le PDF'}</button></div></>}
     {result?.kind==='scan'&&<><div className="scan-header"><div><span className="eyebrow">LE DIAGNOSTIC DE TON CV</span><h2>Un regard sur sa lisibilité.</h2><p>Score indicatif sur le texte, sans garantie de classement.<br/>La mise en page du document d’origine n’est pas évaluée.</p></div><div className={'score '+(result.data.score>=75?'good':result.data.score>=50?'medium':'low')}><strong>{result.data.score}<small>/100</small></strong><span>{result.data.score>=75?'Bonne base ATS':result.data.score>=50?'À améliorer':'À retravailler'}</span></div></div><div className="scan-grid"><div><h3><CheckCheck size={18}/>Points forts</h3><ul>{result.data.pointsForts.map((p,i)=><li key={i}>{p}</li>)}</ul>{!result.data.pointsForts.length&&<p>Aucun point fort identifié.</p>}</div><div><h3><ScanLine size={18}/>Points à améliorer</h3>{result.data.problemes.length?result.data.problemes.map((p,i)=><div className="problem" key={i}><span className={'severity '+(p.severite==='élevée'?'high':p.severite==='moyenne'?'mid':'light')}>{p.severite}</span><p>{p.texte}</p></div>):<p>Aucun problème identifié.</p>}</div><div><h3><Sparkles size={18}/>Mots-clés absents</h3><p className="muted">À ajouter uniquement si tu possèdes réellement ces compétences.</p><div className="keywords">{result.data.motsClesManquants.map((k,i)=><span key={i}>{k}</span>)}</div>{!result.data.motsClesManquants.length&&<p>{job?'Aucun mot-clé manquant identifié.':'Ajoute une annonce pour comparer les mots-clés.'}</p>}</div><div><h3><ArrowRight size={18}/>Recommandations</h3><ol>{result.data.recommandations.map((p,i)=><li key={i}>{p}</li>)}</ol></div></div></>}
    </section>
   </section>
   <section className="education" id="comprendre"><div className="education-title"><p className="eyebrow">COMPRENDRE POUR MIEUX POSTULER</p><h2>Derrière les trois lettres.</h2></div><div className="education-grid"><article><h3>C’est quoi un ATS ?</h3><p>{education}</p></article><article className="checklist"><h3>Qu’est-ce qu’un CV optimisé ATS ?</h3><ul>{['du vrai texte sélectionnable jamais une image','une structure simple avec des sections standards','pas de tableaux/colonnes/zones de texte/en-têtes compliqués','les mots-clés de l’annonce quand on les possède vraiment, avec les mêmes termes','nom et coordonnées clairement lisibles'].map(t=><li key={t}><span><Check size={13}/></span>{t}</li>)}</ul><div className="honesty-bottom"><ShieldCheck size={18}/>Ton expérience est la seule source de vérité.</div></article></div></section>
   <section id="confidentialite" className="privacy-detail"><LockKeyhole size={18}/><div><h3>Tes données, le temps d’une analyse.</h3><p>CV-ATS ne conserve ni fichiers, ni CV, ni résultats et ne journalise pas leur contenu. Les comptes, mots de passe protégés et droits d’accès sont gérés par Supabase Auth. Les fichiers sont extraits en mémoire. Les textes restent dans cette page jusqu’à sa fermeture ou son actualisation. Lors d’une analyse, le CV et l’annonce sont transmis au service Gemini de Google, dont les règles de conservation s’appliquent. L’absence de stockage par CV-ATS ne garantit pas l’absence de conservation chez ce fournisseur.</p></div></section>
  </main><footer><a href="#" className="footer-brand">CV—ATS</a><span>Mettre ton parcours en valeur. En toute honnêteté.</span><a href="#atelier">Retour à l’atelier <ChevronRight size={14}/></a></footer>
 </div>;
}
